name: Lint, test and publish

on: ["push"]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Flake8
      run: |
        pip install flake8
    - name: Flake8
      run: flake8 --ignore=E501,W504 biomaj_download/*.py biomaj_download/download

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requirements
      run: |
        sudo apt update
        sudo apt install libcurl4-openssl-dev libssl-dev
        pip install pytest
        python setup.py install
    - name: Run tests
      run: |
        LOCAL_IRODS=0 NETWORK=0 pytest -v tests/biomaj_tests.py

  pypi:
    runs-on: ubuntu-latest
    needs: [lint, test]
    name: Deploy release to Pypi
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Python install
      run: pip install -U pip setuptools build
    - name: Build a binary wheel and a source tarball
      run: python -m build --sdist --wheel --outdir dist/ .
    - name: Publish distribution 📦 to PyPI
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
